### ISSUE TITLE
`FunctionClauseError` in `handle_info` for exit

### ISSUE THREAD

**Issue by maennchen** [derekkraan/highlander#6]
```
GenServer #PID<0.3098.0> terminating
** (stop) exited in: GenServer.stop(#PID<0.3099.0>, {:function_clause, [{Highlander, :handle_info, [{:EXIT, #PID<0.3099.0>, :shutdown}, %{pid: #PID<0.3099.0>, child_spec: %{id: Acme.Worker, start: {Acme.Worker, :start_link, [[]]}}}], [file: ~c"lib/highlander.ex", line: 90]}, {:gen_server, :try_handle_info, 3, [file: ~c"gen_server.erl", line: 1095]}, {:gen_server, :handle_msg, 6, [file: ~c"gen_server.erl", line: 1183]}, {:proc_lib, :init_p_do_apply, 3, [file: ~c"proc_lib.erl", line: 241]}]}, :infinity)
    ** (EXIT) no process: the process is not alive or there's no process currently associated with the given name, possibly because its application isn't started
    (elixir 1.15.7) lib/gen_server.ex:1031: GenServer.stop/3
    (highlander 0.2.1) lib/highlander.ex:101: Highlander.terminate/2
    (stdlib 5.2) gen_server.erl:1143: :gen_server.try_terminate/3
    (stdlib 5.2) gen_server.erl:1339: :gen_server.terminate/10
    (stdlib 5.2) proc_lib.erl:241: :proc_lib.init_p_do_apply/3
Last message: {:EXIT, #PID<0.3099.0>, :shutdown}
State: %{pid: #PID<0.3099.0>, child_spec: %{id: Acme.Worker, start: {Acme.Worker, :start_link, [[]]}}}
```

**Comment by derekkraan** [comment]
Hi @maennchen, thanks for opening this issue.

This stems mainly from the way Highlander is architected. It should be mostly harmless, but if you want to eliminate these errors (and generally have a more reliable solution), there is also HighlanderPG ([announcement](https://codecodeship.com/blog/2024-04-11-introducing-highlander-pg), [package](https://hex.codecodeship.com/package/highlander_pg)).
